apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:yoQq5Lzroaymmth72d2dlzMrCpK0+0eKR4NIKVVuC9GUoxOfKVvNKQ==,iv:K2mt24ugOaJSx2MQZhU3Luzr0lA+B/4+HDvpBAOJa68=,tag:nw8Nf/E6deyvAH+BrkmP9g==,type:str]
sops:
  age:
    - recipient: age1hy65hzyzgv4hl0awxnstjawmf2293spdkddl5pwxd2lsy976zyjsq99cde
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHTFVzdDNmVHM2TUFjbDVF
        WFNudWJydTdlTG5HR1dGdnErcjQzZUdrbmhrCjNvWWJnM0lUR0ZIZHJ4QlpDdTBO
        QWpLMjJxdysxdDlDcUk2VVV0cW5PUzQKLS0tIEFhY1lnL01FL2hndUJaQkQ4SUIz
        eStwY3ExQUNWVThibE5XckRCbTJQWGcKMr2+d5ZVR69qqc+9eCi84wiy+sNc6V6M
        ftBxEoKXcWnkN6hRwSxIn2k4mkwKry8pNG72UuKBaMkJt8QUZ/qezw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-05T03:58:43Z"
  mac: ENC[AES256_GCM,data:ZVajfq7BF+pEIhrgl6rbpcyp/35BZmWFhN2dWWPxXQO0+csokdlRDboZYkIRhkHJlM37Mb/N7/FkMfEjfF7s55B1Eo+4YRLi5sAvmq3xZCm8873DB4hqR/0X/ZTwpNnEY4Zj8bC3/h3Q2DTZ3vPpvVNoxTh3qTizPqWy/1WP3pk=,iv:QSotYCzA+ARYlE29SaE7SlTMW2irfvW5ns4ISIhxpe4=,tag:pRf0fPQsas/ExTzeBS+iHQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
