apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:9LGhNWbfPvBJTVE=,iv:84dM/8RNXYs66OhZI38NvIw5GQ4bYWcPiRYaipjzApk=,tag:ns8XjTHpmgmOsk4r0b+XsQ==,type:str]
sops:
  age:
    - recipient: age1hy65hzyzgv4hl0awxnstjawmf2293spdkddl5pwxd2lsy976zyjsq99cde
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZK01oaWF6c1NYY0JZSUhZ
        bDMyUGZjSW85bk05VjhYdXV2NlI1VzhvMGprClc3eGFvRmlkZ3RFVzZlYVFubjZj
        MFJVMDV4OE1RTWVpZW0vdlFWY2pZRmcKLS0tIDNlV1JuL0hIVEpSTUt5RmZEQkJx
        YjNaSENiY1pnWjUyeklUWmJib0RuMEUKvzZ54oCRwtr6HoQfsAx4x8f+SRX5Y8z7
        OvOC0CtyOY7NR5FtWfRYIIKtJuz6iWs/sQXnycbEWmTzjcz+l+9/Yg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-05T03:58:43Z"
  mac: ENC[AES256_GCM,data:LP/2IGXufAa94T2tQpHxzeFi06px+qT+eSbs1PiwXKnxRMBvcZVDrukFyBH9Yt9C3X0bILcvDTBEocKAMBxn+K2KAxHWsdGwWHOpR7no32BegiiJFpxh6zfd4gyQwaV0JyG7q2oqoGCyV5r9/Qi9AFbbLotShn1tKEe8mP6mI+o=,iv:iTLinz8fe6gg9wednnAXYzLV+CNo/LvYTU5NVbQw6Ig=,tag:1fn0DWb5AlNBTjVWkkIFwg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
