apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:iee3at5ABAenmBbXCT2mPtDTAIyiKYI3cpCWNUg05kQ=,iv:mwkMHiXdcTvVxU2NW1KJ+OsrxKtvHOMCxPoyMPKj4sI=,tag:4ijGzZzNs0H6FJILeBW8oQ==,type:str]
sops:
  age:
    - recipient: age1hy65hzyzgv4hl0awxnstjawmf2293spdkddl5pwxd2lsy976zyjsq99cde
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwd05Jd1Rpb1lTSlFlbk0z
        cmpJQis1cExqNC9JaFVtak1ydGhQMzYvSHpNCjNOb29adkNyeFRuTEYxbU5NSitD
        SmNUdGQ5YWRIZVg1NFViWFJ4RVBzVE0KLS0tIHQ2SnFRL2tVNFg0UUJXcVQ5Rnhp
        S2x5dHBXdmd1c2tpQlI4OVJtbTJ6SUEKf1OHJnzOD4+/OdbbrroLKJG+r3uid7JP
        xQAW1L6TzVMuA0CqW0GE5qdkaXONAUMbKuTc7JXFwtvA3n+DEJY9dA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-05T03:58:43Z"
  mac: ENC[AES256_GCM,data:GlfVBdQUVOhssNWi0BJb2mRXN+s+Lg6tKJ+Ty2ZcB3OD789E4EuZMWUP9D3sHfZGg6SHU++yu5w0lfXW3Ncp75M8C1ZKKCzjt1j1vbqTplZ2RPVZAbjB1mgsS3zncfr41RJsyNLTxrbvuDDoEAlAT5EZg3yQ+a1JpL7UJ1Sfwt0=,iv:7AHHCYZ+8yCLGX+DLCJqJWSHVhO8+IxxoZ875iAaJJ8=,tag:Q6eCgX8+r1I4dZMc92E9lQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
