---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./config-pvc.yaml
  - ./helmrelease.yaml
  - ./ocirepository.yaml
# - ./volsync.yaml
# - ../../../../templates/gatus/external
