apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:xWFNDUdtRMLn0WGtFU6NZjbL8MQPpj0PrA8gvscpMC11mfMr4AsVkDYOg2c6qjy9FCUlnJfy6/nEZpmTmDWWM2C1tDfIprE4pEQEDkytLI954nAALRhQbS+rq0AgQijd+73u/S1e5CUgeARwzSP/bohbqBFz0bNohynwxB1jS1qz3gfmso65i0oRZ1ReEHtppI8TWhOY7JlhiPmsRmck4fO0gVoZSYSY86vfF5pgyJpDiDfY,iv:riYOUZGoshUnfkFlIrVTFWkfjrGGg6nPtD0RGWfYxGQ=,tag:jbn2jF2xUJvbIkqCZcpxuQ==,type:str]
sops:
  age:
    - recipient: age1hy65hzyzgv4hl0awxnstjawmf2293spdkddl5pwxd2lsy976zyjsq99cde
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkMzNHVTNuSEF3blloZVpH
        NjZrczZHRmZuanNmYzlNTk9TZE5yZlVFU25FCi9XN25BTndsREJEZ2dnWEhEY3dk
        UEk1NzdhQm9aemdJeDRaMjdXNXRKN2MKLS0tICs2TVZSUzM3QjJZaU84Rk1pblV2
        Y21lWE4rellRUUp6dmtMK1NpeHVkQ2MK+/1weEUgyddeZvXL/QB0WgtRfxTv+iC2
        jGSJIJ84LH/ozynYlqj4LGTsEZa/jQm2a7gjICpwTDgev1v76SWb0Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-05T03:58:43Z"
  mac: ENC[AES256_GCM,data:a1a42iLtafJE+8Umg+YDU1kRCskkR7m0pmUzYReEaj8h6r5lj3qpHo+5/RcWeM+n55TZwOiLt13iqjeNd8tn7T/cvNSpCAgXsm4mxCNkPjE44Xxd1jSfNOVeXjTFur2shj5jf5OlBAlpPv7icqSjNMq5wAzUCLulPEKbzfwmjoo=,iv:4bxkqb8BdRynNDbn47D/NEHa1KbilyzkFTbWxlxfAuA=,tag:Piw1XDZxWA5dKlUXJqBSzw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
