# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: onepassword-connect-secret
  namespace: external-secrets
stringData:
  1password-credentials.json: ENC[AES256_GCM,data:/E4muCZCVwq347/yrVvuU19FVa7IUVsIqsphYKBk6YtWe5ALfX3S/rAZTckFs4UbAHltrpG0u8oEXuWyNTAfIX3nbqVAWJW4h7yqWs5ZcsdHhWjdV5945c0WKAwP3C89ufAItJ1vFG013mYub0gVRvkWcX/13nFOiltmeJxbVr0Icp22/o6uNuO/OrumozltBWXdeY8vN6LDKdzYaxAQ5NYWG+nDyT6kPOEOYyBOgcHC2eXiaMszRlGvyZHEGdfx78G5p720lCH7HpQO+B8ZHDGMH+NWnnFHsiMYUCZ2GY1BvgmWuA9cItxBz/LTZeV8PVRKX3VFUV2Kw9PBRlP67Qw+V+eRgpC1OiFEGq48QHe8Wkc5WR2z1XoToULVBOPYAyI3QBITPhIcYPkksM9oLe4AAdPaFSVeoE87udpfzN7hwxDYlcXgc0ZFMK33eLABMsjPHCbXd6Fiv+2HNgjf4AxEn8ky06j3xe2VjiNDkv8ab8gOPx47vLSF2Sc30mZom0lCww7ftCDP9oHHQE1bzU6dXEBGPTFh+wDnDLy8Xmze+c2/P1wBeDwSALP3IlBOI8qc7XxvEQHqVI5T/bVT7zGnBXnGdLzxYjP5xci3a6tjtxICp6gA/p0VdH4g3LBTZb+pT5N0kfEE7DO0Mps8M0tGkXeYXtJKcuGYrEcL/fCaRpgni02U/TlpIM3UZueVBAh26i0rD2ERJE3Se38AfXZ7YU7V28v0826UGEQamLzUMP8bVI1XihvpbmnqQ0JXsF75iKrs0GnG40Eehqbu4WZhQ+LYi8qAdosjgSGFZoCbF74w8JLWZ0RiBAgJ+vWzKur2w+4t5GoTmoJn05mM0tjGveeDzMkQjpxtcECf/AYAXvv81y+7+i1TGT6O9TWfw+mQhJFreVGxkEYdAvlRnWf41XXvq1M/PrAPch2uiTyFypvRpcGSOB9dnl5ZEJC3xhE0FPtO8j0JbFS6Kjx7lGB0J6iii515bYOVidxaB1qGh6NTHoZNUHTKs6UHfBWkrl7WXk5VqGzkXM5UpP1Oee2/Bdy1iFCTEm/qpmY505KW2/pVtj4uWvavTtmEzfFldpOyUfXvzk0KtVhYLeJE6xBZj7hgDBiZ3We77bZcjqeXeo3U87eEVU8RRtISquCrEObKnQu+4l6fr5TElC3O8+sQaI2snteSct+jk56ZfKPrblA7+gZaKguw23C1Yu0f748bYpkas6+XT6wblu1U6EdUZPTWLSFdCEd55/cgGyPcYj8knnmYGn6VnLYjz49G+AtHUtksyTu9fO9gCcSHcb/z5SmEHu23K03bZQ5xXS61snluCmioMaNSJQqAMRmVvwxPW8TX0fTQRvUDr2MBPZowjMb2Ca3JNKZRvyDjzzVo2lcW7h9KlTESqisqpaJnF9je+qVALSU5nP2J+WiHM3xiF0O3+hxnr/1MF9eX+RxHSYRnj9UYTn0MdtvRzuMSjqzuDxPLOXp7tTk5CDu8WgyfTXCjK1eXirpJHVllGafCUEiY9PSjwCaHufv7nQJP1cYyv+hzfeAHsqnvkiLrgBC2aKEvmnvIwgJccKKyFrHE6tcD+76gcZiSVrxMpG+nOeghZ7UNt6uya1Q+BdGFspVhFS24drLyq5IZ37qQ+U2uWAGBbJ0t/qqzgdHZ5zB2sm+nWKC3GvbkieHSsMPJlgBW2VxH1gm9QP44GH+OxzALfYA1UkO5Zj1ovbIedLU8BRzAX2f6mgMRiadDJGd5JTGW2bEz7XZw5hDak6mQHuYTa5dWQhBqDJEY5sf6m1cOHciRgFIrPZbB6ef/vPpmVPYQnV1JxPyw2Eb2PaRuV6L2EFwbXSP7+J3WifZ8fAoviHfesyJ9KRxgsyElGRJP/Do1s6ZZi3NlDLmugX91MIVGno2T2/Bp0i3VTbNNOli6jUby3gtCi7oKBn5D,iv:nVUp44Sd+mmWj8E0NeG+StFxuF5jSWgZQtzo+m0ubq0=,tag:IyUfwYJx91uAOLxmPBfrVw==,type:str]
sops:
  age:
    - recipient: age1x04pdgvml4flx5lewxkqhp3rfngzlgt6gnhqnydskf9u9zhf7euq4qxxxs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrdmpucG5zcWpHbHQ0ZStJ
        Vkc3cjVVK0hHVjRUS3hOWFR6enZId2UwU1hvClVwbVY1Y3dqTnNPbWd0NVk1Qzhl
        OG4yK3FkK3BVRHlrOTVPcWdkRy8rd1kKLS0tIDJKWWVaS2VzK1lPTy9QUGtuNTE1
        N1YwWk9FcjkySithVVhSelc0U3k3dGcKE8en9sn8qXxXKCZmBYqc81MX8vnMFxtR
        yteF3hl+WAhZAL7ueMSqWpSoKcv/ls+EYvBSW9OZZ4jfToPbnvuzkQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-25T06:09:25Z"
  mac: ENC[AES256_GCM,data:9P1BrK2UsSxhBDBrRvLcFJTZiqYmm5Y6/O46O6danm/S9GirX0c2TGP2f/hGcHYCCeMql4tzCVrWZGkDESwIjk7EwzF7nj3Ccw6zjF5NdcLd/bwReG1T1w5ie/BwXdX7nORakr5dK3jy3U92Gpdo+WWACjeL0jCZqyXvn8QFZRQ=,iv:ipAS6zYN/nan6JIi8Cgb/U+d299p4lcMZIW4e96BFoQ=,tag:oEacp2LkOyuPqhEjwycfBQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: onepassword-connect-token
  namespace: external-secrets
stringData:
  token: ENC[AES256_GCM,data:aARTRFEikmezIUlbYNrxmiosxtBCOnt8iz53ipMnGCcFvXGqTKXWYPLtZZrhhD6wI+8c5/kJ2QDCHP4jKksp91zRfanLeHthl31+B4JLBAnpX5iKnd7avNrh2aA9vx1bVjpV+UNV+AO9ZcRNVEJWcsFybH3+SnPF7mtWwKzTF1R65O2mMwepz7BW4j60R02avpBiRmsyV9IerKWn59yTBOJ7/kET/YoX2YtrC9RQwb5ISkBVpPIHhJc64mJRfSmwpCNmqlPWmd4Z8gXZb3fHhlb9l+bMvR6sYRTZF2lTee7Q6AkCinaxa8NyvndTmyBXIU7SPUMQKfTs8WvLtoQuQofRSRhf3ytbcTyf2ZyXrOqfyU6EGOJ62EKG9hWDk4cnjs7U8U6PIeVjjutRtMHHMSqTtg+Vy4JMplI+Y7CEyyFejAca2UA2HqfbZnS5FQOSv8vrbtYOjwGiJZ2At535xnljvFtJ69DZn9HzLCuluE1433/dC+p7ikvlHDn6GmMkRG1/+IiL21FrhZYGhZTVF2+ilD5YgEmAvF7MBdhdMqfAVs3//7aK8RE0hzk76FUJWBNG4Hve4z58BqWfI0dMhgCHHLBYwH1iJNF4CWvIY5+MwPLBertO4i0ni0Wju/Y+hLRMRNsWSUiAA3sVxGnSLE8kFUTTuIAUf8H3I4G6Fw30I/o5VS7DedGNTKlxI0FjA3F2I0ikt8K/QikjtGa71wRgZrH/zos7/GYsJaPRmy1zOrbw1QRbTFh5OJBquU1mvf7OTx8FEH2V9XT1/eWwJSHioNutJ1LEz21ugKJBWZPX//Ky8lgKSqzrQ/pAnK4c7Oza5l/g7lrYspvZWKfym8i/,iv:2tHDqXZNv1rgHhCG1NUPR/h01MT9rfkmNaJReZFoY6M=,tag:puEeqW98nRSgoe0+MsfZcg==,type:str]
sops:
  age:
    - recipient: age1x04pdgvml4flx5lewxkqhp3rfngzlgt6gnhqnydskf9u9zhf7euq4qxxxs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrdmpucG5zcWpHbHQ0ZStJ
        Vkc3cjVVK0hHVjRUS3hOWFR6enZId2UwU1hvClVwbVY1Y3dqTnNPbWd0NVk1Qzhl
        OG4yK3FkK3BVRHlrOTVPcWdkRy8rd1kKLS0tIDJKWWVaS2VzK1lPTy9QUGtuNTE1
        N1YwWk9FcjkySithVVhSelc0U3k3dGcKE8en9sn8qXxXKCZmBYqc81MX8vnMFxtR
        yteF3hl+WAhZAL7ueMSqWpSoKcv/ls+EYvBSW9OZZ4jfToPbnvuzkQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-25T06:09:25Z"
  mac: ENC[AES256_GCM,data:9P1BrK2UsSxhBDBrRvLcFJTZiqYmm5Y6/O46O6danm/S9GirX0c2TGP2f/hGcHYCCeMql4tzCVrWZGkDESwIjk7EwzF7nj3Ccw6zjF5NdcLd/bwReG1T1w5ie/BwXdX7nORakr5dK3jy3U92Gpdo+WWACjeL0jCZqyXvn8QFZRQ=,iv:ipAS6zYN/nan6JIi8Cgb/U+d299p4lcMZIW4e96BFoQ=,tag:oEacp2LkOyuPqhEjwycfBQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
