# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: onepassword-connect-secret
  namespace: external-secrets
stringData:
  1password-credentials.json: ENC[AES256_GCM,data:7poccRFmiUyH6+YmdsNEYgEm029nFDq7QAO/Hfr+cRUoIkBwafNn8vwzvQg9aikKSdQk8B9pQhJ1rnRyM+1jcMZTGrBS6YkBQXzNv+/kPHgISN5LFTznekl1kjI4aOYFVPheCFebra2OODdVi+Fn0WM2lusmLFghir9FzOFHVwtxybhDSKJ7eecbqJKzTblhUTVA50HQUZYpigHnKBnCtmZnhtbkokDzW3YjvMXPCCdlGhOdYN3oaqayyWfsuElj6g2ZQdlCojXwwRPqUW6BHYub/xENQpjsQ+fodLv+xbpmE36HVACzXE/5Fw2GlgXPmLR0gSXwXXwHT4ydhK6fVP+oF5dSMT7a7dUOt3BQn8hFKrCSGWbYotIAqPhvngvxnUmlkFuLyD6GbQdld+LyLCbYkXNCoRGvSRuMshuN6r9Kkmc43H62U0HCLKY8nGJlqox7rRcJCY2b3S0VD23JngYOOEFZ9WcSQPDVGecK6SSAWwrMFqkyM0qqtNfksYZgkbnIppOI84N6VAh0Yt0m058KfKUojqWOiMB5N+RRqR7CSdgXVUEEwS+LRXWIYpagd91MsCoYMIOX2XcuFRGBZ+lINWKYgePz9YnymiMwglMmKoHwtR0xlLAzVfOWtpWfr8nB+efTSNu5bImBzUjOM5Zj0xsqKcx2U7far+ql7kSOAdHnsTqraxL+CP88+AhTDZnMeXYBDtvHlXtwDpUCLBqHI4Ry9WAbqxFr79kXOScMAWMyt4hULqM9m2sdwcArrruvYvyPBy84lKopSRfUkbazoPVo8JGinS5vsyBtac9UhS2KRil+X2OaF7VppJaBHTTv4ULwO8QkEvVoshgxsDOts4u97VH9fE8KmUegMmLNz/s1DVaVHFnzfg5Ans0Ya8Pu2SR5U26mNyn3buK2sqlN1LOvDlwPJYcmoRMx+68WVkooPyBHb40mMmuo0jwy3v+Pfxo0M0VIIGZU+/YFGKkgMW26eD8/7GB6k8cKLixxHNbaAV6A6dFyGBV3SZcapCHX3t/KKgKw+4ePprfXKZvVZRRkghf+ZnfcTJlVUItX5yH3knnkJfqL10D0aOq7U0sZgwvbY5f7Q77f/geFcJMPxkuP0oYheubO+UlCnYuwp8IWt+Eduxh9qEWd3BG3zrwQDP/5ra0lBuSMbQXZY0Jk4Nk/tKQ7R33RUS1nuyheToGDQR56Eo1PjeRKoaKoGKuo65dg5yeL+lWthprc7Asllxq0kcAj/cDABD9a9BYiBcmL2T66jJ/eCBvbZ4v7Oe6fwe0ybJW0Sv4HQT7xo88+8EO2GbvEkMaS8v4tqDRGd2TuiH2wxbGu5AsXD60GweOrn4JBRLqt42z5HCgPuU9kzTrk6HKsg6MxASFf/RXNR554bUFLrEkBF1/rhi3CkIPeMnaCwSJOXnVxc9zb9k171fPOXfB/aUcSVZlDnY0KBh2dzx9nMjyB23b6waL4k/1dM+ZRENA+OL+PqQXfWR+4PnIMeUUXk32BtA9UzXWVpJkqWfq6zZyNeF4VtmvT8ZD+VEP2yUHMqOzD4uWjWU77DSapmX3BEhGqYyMJ0zL9wmjcktHRo12tiD4oVQTKkrIw0oZ7xz7PbbC/DWALlXhp8wRfLY13zmQfZQqiKLsv+y37YR0b36RRlH2deECkiGzH97T31Ch5qW9adijhQ/NTv7y8OgaTdH1sVHuHBzDJ5H7QyKMiJAQIgPvQRmchyeCW5g3mkakHYEfD03XuHVZzaRv4PgFSKkiHq3u7axx5mM8DVn5TVVKjW81zscV1kEOSK97vAzB3J+JBKd8K4TXkJpVXScjARG8BguqrDIW/MmRIwt+Y34CMu7FeAsk57FSoVShxvNLzK+dWpPHyIxvYJ4Xjgs/OoYvcFNcbmiMY4Fc+NeGJrIHrUtkrFoHGdlRuSbHHnowuEX0F,iv:FdLFZ8UT6PKGj0xgTv3T5uQ/n4mq9PQcggzkn+YEw70=,tag:5lIlwVxYzBuX2aQDR9oBPg==,type:str]
sops:
  age:
    - recipient: age1hy65hzyzgv4hl0awxnstjawmf2293spdkddl5pwxd2lsy976zyjsq99cde
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMdllrbGlUMkYxWDlBUEtT
        NlpVK0wvYXc3ak9lL2N6SUlJdFAvTEJyYTJrCm84clBlaFlQNWZYelFwcEJVSG1s
        WDRuZ28vKzN3Z3lWUlhwU1lESjdwSmsKLS0tIGZZVVB3THBRejhUNnNsNzgrZ1Js
        TFM5UFZRSUc5MzZVRWxrRG4wWU1oVGsKArI1kcRYWAGRg2/M9dyEl4DXfkZz1Grb
        vcHebntD3ZkJyaAJQIrTVU0xR9d9wppFmqbXT99bd15M8O5x+Ow1hQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-05T08:03:59Z"
  mac: ENC[AES256_GCM,data:nLMycXyM/vItBGqaPP7RBULd03TSOSbNBv1SA8Ax4OcdGwz541HYT8JgCG7wew0QUjFN6j1E9RiZ4iGvhGcXaXiswTZK5mOCeeC557tG/iNsLh673Nft2w8Kc+1Q6OavTPfwoGe3N/kpSIHMrR5izUf+wc3BPainZwt1qcetojs=,iv:c/PWP0BQyLxD8JZBTdfqe79HkcToLxgMPnDZPl9aCfI=,tag:3m2OZJuc6/VP7yr7odU3uQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: onepassword-connect-token
  namespace: external-secrets
stringData:
  token: ENC[AES256_GCM,data:OXcBp+Yk/N36p5FnnX25JgCXjuorG000kANNvL9efEjm6v0JL7zp/tHsd+0q3FjTLuLeJhvK+D+TIADp+xpfKotmU2Ify5RpeU6lLHx5cXUdMVIXpmitS0+pAJ8/3edJkfmcZ3Hj3PLxuWW/MMKy0kfOaUsFU9yV+YWLGYV+o/HdF6JaTTAYE8fWN50xqD0zxkULKtfH56ysFlGjlGQ1ep/uohdYEMHSjzSWZq5JLAHFr3pMCgGaGA8XsdOQ+WBzuLiO0/izo6eJIXx+SdieYchtJ52jabgyiNkBYjQW5fP9VjZuwsSil74W3s61L/DqyzNxG9Y7Qg3+o0vl1PHnbBagyxUDMzw+ji+sfacozdQpRGkTFgRoSH7bY9C/Jg4btvYnKqF0/ZwJu5MOvePMTHhumvrSTCJ4jopSu0QjfsDzvpk8E9wzqrykIslLEJM4GO7fle2ILlzkNchJUA/u/FnT4OQvP35pBXLD/SokNhnMDh2tLAaxm989j043YE6yJxzGoF0uHih7/3JVI05c4dSG+Mq1WwE2ciGNBsrXV3bA2SBlQCrPhtchywM+WPkQy3qWBU3vTe10R0IQgX3tn+voQotn7fLBJdIq/8BStCZUXXWNa3vXGweUdJnRu9W/TU9l10Vy5t17iMSART1PAWNzku0anHoU6qGwn7sydcU3at3L5ZJjeej8Ftgexdt+sDe99OXn4o4G8sxnimGWJ4XE2yjTnR893KO/HZQAxojAZF33Em1F4+e00SLQPoA1rYQ2uai/LjsmkIglKakeWA9LxpU/9h4imDLXKtnQiBIAJMJJZnK5ID1NTJz8shFclnF4H6odXbFTfcSbvjY9jAq5,iv:y6jrwAr/6KD4xj1ohH0LM3vZRo27R7yBdLJPdtR9O70=,tag:8qAxRn0PfIp0XVnM4YX0Gg==,type:str]
sops:
  age:
    - recipient: age1hy65hzyzgv4hl0awxnstjawmf2293spdkddl5pwxd2lsy976zyjsq99cde
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMdllrbGlUMkYxWDlBUEtT
        NlpVK0wvYXc3ak9lL2N6SUlJdFAvTEJyYTJrCm84clBlaFlQNWZYelFwcEJVSG1s
        WDRuZ28vKzN3Z3lWUlhwU1lESjdwSmsKLS0tIGZZVVB3THBRejhUNnNsNzgrZ1Js
        TFM5UFZRSUc5MzZVRWxrRG4wWU1oVGsKArI1kcRYWAGRg2/M9dyEl4DXfkZz1Grb
        vcHebntD3ZkJyaAJQIrTVU0xR9d9wppFmqbXT99bd15M8O5x+Ow1hQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-05T08:03:59Z"
  mac: ENC[AES256_GCM,data:nLMycXyM/vItBGqaPP7RBULd03TSOSbNBv1SA8Ax4OcdGwz541HYT8JgCG7wew0QUjFN6j1E9RiZ4iGvhGcXaXiswTZK5mOCeeC557tG/iNsLh673Nft2w8Kc+1Q6OavTPfwoGe3N/kpSIHMrR5izUf+wc3BPainZwt1qcetojs=,iv:c/PWP0BQyLxD8JZBTdfqe79HkcToLxgMPnDZPl9aCfI=,tag:3m2OZJuc6/VP7yr7odU3uQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
