---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: downloaders
components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  # Flux-Kustomizations
   - ./sabnzbd/ks.yaml
#  - ./angelnu.yaml
