apiVersion: v1
kind: Namespace
metadata:
  name: downloaders
  labels:
    routed-gateway: "true"
    goldilocks.fairwinds.com/enabled: "true"
  annotations:
    volsync.backube/privileged-movers: "true"
