apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:RjLNWp9Sss5HkzoBgKWFYlL8mT9EqoaftCxpoYzNO3p/hHpwuuvAgg==,iv:DvDAxhyC712i8qBY6RL0tgxuZ2cDboA7K4zCYoIdKt8=,tag:ZDP4AW2F/12mIQcIi2rYSA==,type:str]
sops:
  age:
    - recipient: age1hy65hzyzgv4hl0awxnstjawmf2293spdkddl5pwxd2lsy976zyjsq99cde
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvVWQ0UDBZMW1rV0ZMRDRG
        VEg0QjBNeHkyVGZEeXUzK05wZ213RFZ0VWxNCmZ0Y0dIdzVvWXhzRzE1WXNDSk1l
        WGxCNFlycWtZVzZHN2lDSmJCL0hRWVEKLS0tIHpFblYvV1FsQ3ZtdmFYOVJONDU1
        MlVBUUsrdUNCYlJYdVRZdDA1Q2RQM2sKCFUgRnMonA8xJ6/o2Y4N6dBq/SJAFqLt
        cidXMFWJHs4h4JRqStLhPwXY8gNK4m+CSUHL/IG/XnWO0XzdAniQjg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-05T03:58:43Z"
  mac: ENC[AES256_GCM,data:jMib250NeeE0TjIs/CB21sX1mJNY3SdIc307EUE6q7g8LXd+pPz5ZJ2fGqOeRb4YC4Ulti7XYC+iUyX4gSMM8CLn5Pj4u1yUxsk61F/4jVX9kut3qmp78Jw2S05J1u6U6BDp0+BME2A1l7HWs4RseZv45noVokmJGPViM5sWDLc=,iv:RcY6lA+wd7v9CJkEeZCCP73BCNzJmVBhfwsV5VMBIr4=,tag:Qj5c/DNqSHiSGxXKtKeShw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
