
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: organizers
components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./sonarr/ks.yaml
  - ./prowlarr/ks.yaml
  - ./radarr/ks.yaml
